# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Recommendation links widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: links
        # Names and URLs of the sites
        links:
            PetPaw: 'https://petpaw.app'
            fluda: 'https://pub.dev/packages/fluda'
            DevTiles: 'https://github.com/simonpham/Tiles-For-Developers'
            Devetter: 'https://github.com/simonpham/Devetter-Plugin'
    # Google AdSense unit configurations
    -
        position: right
        type: adsense
        # AdSense client ID
        client_id: 'ca-pub-8469309022192575'
        # AdSense AD unit ID
        slot_id: '6887389745'
