name: simon_workspace
publish_to: "none"

workspace:
  - apps/simon_web
  - modules/simon
  - packages/core
  - packages/core_remote_data
  - packages/core_remote_data_pb
  - packages/icons
  - packages/ide_layout
  - packages/l10n
  - packages/platform_utils
  - packages/ui_markdown
  - packages/utils

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
