app = "nowis-api"
primary_region = "sin"

[processes]
  nowis = "nowis"

[build]
  builder = "paketobuildpacks/builder-jammy-base"
  buildpacks = ["paketo-buildpacks/go"]
  [build.args]
    BP_GO_TARGETS = "./cmd/nowis"

[env]
  ENV = "production"
  SF_NOWIS_INTERNAL_ADDRESS = ":22399"

[[services]]
  auto_start_machines = true
  auto_stop_machines = true
  internal_port = 22399
  processes = ["nowis"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

    [services.ports.http_options]
      h2_backend = true

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
