name: simon

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../packages/core
  core_remote_data:
    path: ../../packages/core_remote_data
  core_remote_data_pb:
    path: ../../packages/core_remote_data_pb
  design_system:
    path: ../../packages/design_system
  ide_layout:
    path: ../../packages/ide_layout
  l10n:
    path: ../../packages/l10n
  platform_utils:
    path: ../../packages/platform_utils
  ui_markdown:
    path: ../../packages/ui_markdown
  utils:
    path: ../../packages/utils

flutter:
  uses-material-design: true
