syntax = "proto3";
import "get_posts.proto";
import "get_post.proto";
import "get_sidebar_posts.proto";

package nowis;

option go_package = "protobuf/generated/nowis";

service NowisService {
  rpc GetPosts(GetPostsRequest) returns (GetPostsResponse) {}
  rpc GetPostById(GetPostByIdRequest) returns (GetPostByIdResponse) {}
  rpc GetPostBySlug(GetPostBySlugRequest) returns (GetPostBySlugResponse) {}
  rpc GetSidebarPostsByTags(GetSidebarPostsByTagsRequest) returns (GetSidebarPostsByTagsResponse) {}
}
