name: simon_web
description: "Simon"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  simon:
    path: ../../modules/simon

  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  l10n:
    path: ../../packages/l10n
  platform_utils:
    path: ../../packages/platform_utils

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/themes/

  fonts:
    - family: Iosevka
      fonts:
        - asset: assets/fonts/iosevka-ss08-regular.ttf
        - asset: assets/fonts/iosevka-ss08-italic.ttf
          style: italic
        - asset: assets/fonts/iosevka-ss08-bold.ttf
          weight: 700
        - asset: assets/fonts/iosevka-ss08-bolditalic.ttf
          style: italic
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Italic.ttf
          style: italic
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lora-BoldItalic.ttf
          weight: 700
          style: italic
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono-ThinItalic.ttf
          weight: 100
          style: italic
