name: l10n
publish_to: "none"

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: "flutter"

  flutter_localizations:
    sdk: flutter
  intl: any

flutter:
  generate: true
